#!/bin/bash

# TO USE: copy this to your ~/.bash_completion file
# 
# I've spent a little time trying to figure out how to integrate this into the build system,
# but I haven't figured out a good way to do it

#!/bin/bash
_sbn_complete() {
  local cur prev
  _get_comp_words_by_ref cur prev

  COMPREPLY=()

  if ! [ -z ${SBN_LIB_DIR+x} ]; then
    if [[ ${prev} == -m ]] ; then
      COMPREPLY=( $(ls "${SBN_LIB_DIR}" | sed -n -e 's/^libsbnanalysis_//p' | sed -n -e 's/\.so//p' | grep "${cur}"))
      return 0;
    fi
  fi

  # fall back to built in completion
  _filedir
  return 0;
}
complete -F _sbn_complete sbn
complete -F _sbn_complete sbn-postprocess
