#include "canvas/Persistency/Common/Assns.h"
#include "lardataobj/RecoBase/Slice.h"
#include "lardataobj/RecoBase/Vertex.h"
#include "lardataobj/RecoBase/Track.h"
#include "lardataobj/RecoBase/PFParticle.h"
#include "lardataobj/RecoBase/Shower.h"
#include "lardataobj/RecoBase/MCSFitResult.h"
#include "lardataobj/RecoBase/Hit.h"
#include "lardataobj/AnalysisBase/T0.h"
#include "sbncode/TPCReco/Products/MergedTrackInfo.hh"
#include "sbncode/TPCReco/Products/VertexHit.h"
#include "sbncode/TPCReco/Products/Stub.h"
#include <vector>
#include <utility>
