#ifndef _sbnumurecodata_TruthMatch_hh
#define _sbnumurecodata_TruthMatch_hh

#include "TVector3.h"

#include "ana/SBNOscReco/Data/Mode.h"

namespace numu {
struct TrackTruthMatch {
  bool has_match;
  bool mctruth_has_neutrino;
  TVector3 mctruth_vertex;
  int mctruth_origin;
  int mctruth_ccnc;
  int mcparticle_id;
  float completion;
  int match_pdg;
  TrackTruthMatch():
    has_match(false),
    mctruth_has_neutrino(false),
    mctruth_vertex(-1, -1, -1),
    mctruth_origin(-1),
    mctruth_ccnc(-1),
    mcparticle_id(-1),
    completion(-1),
    match_pdg(-1) {}
};

struct TruthMatch {
  bool has_match;
  InteractionMode mode; //!< mode of the interaction
  TrackMode tmode;
  int mctruth_vertex_id; //!< index of the truth vertex into the list of MCThruths. -1 if no match
  int event_vertex_id; //!< index of the truth vertex into the list of truth vertices generated by this class. -1 if no match
  int mctruth_track_id; //!< index of the primary track into the list of MCTruths. -1 if no match.
  int event_track_id; //!< index of the primary track into the list of truth vertices generated by this class. -1 if no match.
  float truth_vertex_distance;
  bool is_misreconstructed;
};
}
#endif
